### ISSUE TITLE
States are not listing as it is trying to require /lib/db/states.in

### ISSUE THREAD

**Issue by Prabhakarank** [thecodecrate/city-state#3]
Dear Author, 
        I  have installed the city-state (0.0.11) and tried to load countries and its loading but states are not loading as in my system I am getting the following issue.

Errno::EACCES: Permission denied - /home/bitla-b10/.rvm/gems/ruby-1.9.3-p547/gems/city-state-0.0.11/lib/db/states.in
from /home/bitla-b10/.rvm/gems/ruby-1.9.3-p547/gems/city-state-0.0.11/lib/city-state.rb:104:in `initialize'

It seems its requiring some missed files.

Thanks in Advance.

**Comment by Prabhakarank** [comment]
Dear Author, 
         As I mentioned in the previous post, one more issue I am facing for CS.update

Errno::EACCES: Permission denied - /home/bitla-b10/.rvm/gems/ruby-1.9.3-p547/gems/city-state-0.0.11/lib/db/GeoLite2-City-Locations-en.csv
from /home/bitla-b10/.rvm/gems/ruby-1.9.3-p547/gems/rubyzip-1.1.7/lib/zip/entry.rb:582:in `initialize'

It also seems like the previous mentioned. Thanks.

**Comment by loureirorg** [comment]
Hi @Prabhakarank,

can you execute these 4 commands below (at shell prompt) and put the returns here?
1) `gem which city-state`
2) `ls -lh /home/bitla-b10/.rvm/gems/ruby-1.9.3-p547/gems/city-state-0.0.11/lib`
3) `whoami`
4) `groups`

The command _(1)_ is to make sure of the gem path (probably is `/home/bitla-b10/.rvm/gems/ruby-1.9.3-p547/gems/city-state-0.0.11`). The command _(2)_ is to check who is the owner/group and the permissions of folder. The commands _(3)_ and _(4)_ is to check which user and groups are you.

My guess is that you installed the gem with an user (like root, by using `sudo`) and your actual user is not the same that you used to install, neither are in the same group. 

If is that, I can fix this issue in the gem, but I want to make sure if is really that.

**Comment by Prabhakarank** [comment]
Hi, 
    Please find the required details,
1) gem which city-state --->/home/bitla-b10/.rvm/gems/ruby-1.9.3-p547/gems/city-state-0.0.12/lib/city-state.rb
 2) ls -lh /home/bitla-b10/.rvm/gems/ruby-1.9.3-p547/gems/city-state-0.0.11/lib
total 16K
drwxr-xr-x 2 bitla-b10 bitla-b10 4.0K Mar  9 18:11 city-state
-rw-rw-r-- 1 bitla-b10 bitla-b10 6.6K Mar  9 18:11 city-state.rb
drwxr-xr-x 2 bitla-b10 bitla-b10 4.0K Mar  9 21:04 db
3) whoami ---> bitla-b10
4) groups ---> bitla-b10 adm cdrom sudo dip plugdev fuse lpadmin sambashare.

And now installed the gem city-state (0.0.12) and working fine. 
Thanks for the reply.

**Comment by loureirorg** [comment]
I've corrected the permissions in this new 0.0.12 version, this is why it worked now :)

Thanks for reporting this issue.

**Comment by dpasichnyk** [comment]
Have same issue on 0.0.12/0.0.13

1) /opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/city-state-0.0.13/lib/city-state.rb
2) - 
3) vagrant
4) vagrant

**Comment by loureirorg** [comment]
Hi @dpasechnik,

can you please run these 2 commands and put the results here?

1) ls -lh /opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/city-state-0.0.13/lib
2) ls -lh /opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/city-state-0.0.13/lib/db

**Comment by dpasichnyk** [comment]
ls -lh /opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/city-state-0.0.13/lib
total 16K
drwxr-xr-x 2 root root 4.0K Sep 16 14:30 city-state
-rw-r--r-- 1 root root 6.8K Sep 16 14:30 city-state.rb
drwxr-xr-x 2 root root 4.0K Sep 16 14:30 db

ls -lh /opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/city-state-0.0.13/lib/db
total 7.2M
-rw-r--r-- 1 root root 3.9K Sep 16 14:30 countries.yml
-rw-r--r-- 1 root root 7.2M Sep 16 14:30 GeoLite2-City-Locations-en.csv
-rw-r--r-- 1 root root   26 Sep 16 14:30 states-replace.yml

**Comment by loureirorg** [comment]
right. It's a permission problem.

You can quickly fix it by running:

```
chmod g+r /opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/city-state-0.0.13/lib/db/*
```

anyways, I'll fix this on the 0.0.14 version

**Comment by loureirorg** [comment]
right. It's a permission problem.

You can quickly fix it by running:

```
chmod g+w /opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/city-state-0.0.13/lib/db/*
```

anyways, I'll fix this on the 0.0.14 version

**Comment by DaKaZ** [comment]
+1 in needing this fixed.  Every new server at AWS we have to manually fix.  Appreciate all the efforts, we love the city-state gem!!

**Comment by Haar** [comment]
@loureirorg +1 Any idea when the 0.0.14 release is likely?

**Comment by gerardp** [comment]
+1 
i have the same error!

**Comment by gerardp** [comment]
Permission denied - /Library/Ruby/Gems/2.0.0/gems/city-state-0.0.13/lib/db/states.es

ls -hl  /Library/Ruby/Gems/2.0.0/gems/city-state-0.0.13/lib/db/
total 14632
-rwxrwxr-x  1 root  wheel   7,1M 29 ene 13:56 GeoLite2-City-Locations-en.csv
-rwxrwxr-x  1 root  wheel   3,9K 29 ene 13:56 countries.yml
-rwxrwxr-x  1 root  wheel    26B 29 ene 13:56 states-replace.yml

**Comment by januszm** [comment]
`Permission denied @ rb_sysopen - /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/city-state-0.0.13/lib/db/states.us`

Amazon Elastic Beanstalk , Amazon Linux, Rails 5
Production environment

**Comment by januszm** [comment]
When does the `states.us` (or other country) file creation occur? It's highly possible that gemfiles owner will be root or different user in various deployment scenarios. 

### Update

Looks like it happens during runtime. This makes it pretty unusable in several production environments.

```
def self.countries
    if ! File.exists? COUNTRIES_FN
      # countries.yml doesn't exists, extract from MAXMIND_DB
      update_maxmind unless File.exists? MAXMIND_DB_FN
```

**Comment by harshad26** [comment]
I have same issue like @januszm. Did you solve it @januszm then paste here so It will help me and other as well.

**Comment by januszm** [comment]
@harshad26 I stopped using this gem and wrote my own tiny lib for US states.

**Comment by Faisal-nfl** [comment]
@loureirorg 
What you did in 0.0.13 to solve the issue?
Kinldy tell us so that we can at least use in our separate fork

**Comment by Faisal-nfl** [comment]
its taking to much time without any success,
So what I did for now
from console `sudo bundle exec rails c development`
than
```
countries_codes = CS.countries.except!(:COUNTRY_ISO_CODE).collect {|p| p[0] }.compact
#it contains  country codes like :US etc
countries_codes.each do |countries_code|
  CS.get countries_code
end
```
it created all required files in ...lib/db/ which were suppose to create runtime.
Now working

**Comment by cuongnc0211** [comment]
I have the same problem and this solution work for me:
$gem which city-state 
-> /Users/macbook/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/city-state-0.0.13/lib/city-state.rb
$sudo chown -R $(whoami) /Users/macbook/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/*

**Comment by RailsCod3rFuture** [comment]
When will they push out the the new gem with the fixes? I had to manually add permission for 3 different workstation PCs. Please, get the latest build, up and running.
Thanks.

**Comment by shaship2** [comment]
@loureirorg : Could you please let us know if you are planning to fix this bug ? Without this fix, using this gem in production environment might be a headache.

**Comment by Ankitap123** [comment]
I have got the same issue..i resolved it ,n since m new to all this...what should i do since i can see the issue is open?

**Comment by kushagra-03** [comment]
Thanks a lot for the great gem, really appreciate it, although seems like this is still an issue, and this needs to be updated in production every time a new machine is provisioned.
Any plans to fix this?

**Comment by siddhip77** [comment]
I am using [city-state (1.1.0)] and getting this error on production, however its working fine on local. How can I fix this at production?
